# Generated by Django 4.1.2 on 2022-10-28 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linksmedia_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmedia',
            name='iamge',
            field=models.ImageField(default=datetime.datetime(2022, 10, 28, 14, 0, 52, 283970, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
