# Generated by Django 4.1.2 on 2022-10-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_linksmedia_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linksmedia',
            old_name='iamge',
            new_name='image',
        ),
    ]
