# Generated by Django 4.1.1 on 2022-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('SSLcommerz', 'SSLcommerz')], default='Paypal', max_length=50),
        ),
    ]
